# Generated by Django 6.0.3 on 2026-03-15 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название отделения')),
                ('icon', models.CharField(max_length=50, verbose_name='Иконка/Эмодзи')),
                ('description', models.TextField(blank=True, verbose_name='Краткое описание')),
            ],
            options={
                'verbose_name': 'Отделение',
                'verbose_name_plural': 'Отделения',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название мероприятия')),
                ('day', models.CharField(max_length=2, verbose_name='Число')),
                ('month', models.CharField(max_length=20, verbose_name='Месяц')),
                ('location', models.CharField(max_length=255, verbose_name='Место проведения')),
                ('button_text', models.CharField(default='Записаться', max_length=50, verbose_name='Текст на кнопке')),
            ],
            options={
                'verbose_name': 'Мероприятие',
                'verbose_name_plural': 'Афиша',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок на главном экране')),
                ('subtitle', models.TextField(verbose_name='Подзаголовок (описание)')),
                ('logo_text', models.CharField(default='Школа им. С. Бекмуратова', max_length=100, verbose_name='Текст логотипа')),
                ('about_title', models.CharField(default='О нашей школе', max_length=100, verbose_name="Заголовок 'О школе'")),
                ('about_description', models.TextField(verbose_name='Текст описания школы')),
                ('about_image', models.ImageField(blank=True, upload_to='about/', verbose_name="Фото для блока 'О школе'")),
                ('footer_copy', models.CharField(max_length=255, verbose_name='Текст копирайта в футере')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='Адрес')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='Телефон')),
            ],
            options={
                'verbose_name': 'Основные настройки',
                'verbose_name_plural': 'Основные настройки',
            },
        ),
    ]
