# Generated by Django 6.0.3 on 2026-03-15 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='hero_image',
            field=models.ImageField(blank=True, upload_to='hero/', verbose_name='Главное фото (фоновое)'),
        ),
    ]
