# Generated by Django 6.0.3 on 2026-03-15 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_application'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='instagram_url',
            field=models.URLField(blank=True, help_text='Вставьте ссылку на Instsgram', max_length=500, null=True, verbose_name='Ссылка на Instagram'),
        ),
    ]
