# Generated by Django 6.0.3 on 2026-03-16 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_sitesettings_instagram_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='icon',
            field=models.ImageField(blank=True, upload_to='departments/', verbose_name='Иконка/Эмодзи'),
        ),
    ]
