# Generated by Django 6.0.3 on 2026-03-16 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_department_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='icon',
            field=models.CharField(max_length=50, verbose_name='Иконка/Эмодзи'),
        ),
    ]
