# Generated by Django 6.0.3 on 2026-03-16 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_department_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='icons/', verbose_name='Иконка (картинка)'),
        ),
    ]
