# Generated by Django 6.0.3 on 2026-03-16 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_remove_event_button_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='button_text',
            field=models.CharField(default='Записаться', max_length=50, verbose_name='Текст на кнопке'),
        ),
    ]
