# Generated by Django 6.0.3 on 2026-03-16 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_event_button_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='button_text',
        ),
    ]
