# Generated by Django 6.0.3 on 2026-03-16 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_sitesettings_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название награды')),
                ('image', models.ImageField(upload_to='rewards/', verbose_name='Изображение награды')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок сортировки')),
            ],
            options={
                'verbose_name': 'Награда',
                'verbose_name_plural': 'Награды',
                'ordering': ['order'],
            },
        ),
    ]
