# Generated by Django 6.0.3 on 2026-03-16 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_reward'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='ФИО учителя')),
                ('photo', models.ImageField(upload_to='teachers/', verbose_name='Фотография')),
                ('specialty', models.CharField(max_length=100, verbose_name='Специализация (напр. Фортепиано)')),
                ('experience', models.CharField(blank=True, max_length=100, verbose_name='Стаж/Регалии')),
                ('description', models.TextField(blank=True, verbose_name='О себе')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок вывода')),
            ],
            options={
                'verbose_name': 'Учитель',
                'verbose_name_plural': 'Наши учителя',
                'ordering': ['order'],
            },
        ),
    ]
