# Generated by Django 6.0.3 on 2026-03-16 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_gallery_priceplan_review_studentpride'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Gallery',
        ),
        migrations.DeleteModel(
            name='PricePlan',
        ),
        migrations.DeleteModel(
            name='Review',
        ),
        migrations.DeleteModel(
            name='StudentPride',
        ),
    ]
