# Generated by Django 6.0.3 on 2026-03-17 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_review'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
