# Generated by Django 4.2.7 on 2026-03-26 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_alter_application_id_alter_department_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='age',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Возраст ученика'),
        ),
        migrations.AddField(
            model_name='application',
            name='message',
            field=models.TextField(blank=True, null=True, verbose_name='Комментарий'),
        ),
    ]
