# Generated by Django 4.2.7 on 2026-04-04 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_sitesettings_facebook_url_alter_application_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='contacts_background',
            field=models.ImageField(blank=True, null=True, upload_to='backgrounds/', verbose_name='Фоновое фото для страницы Контакты'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='departments_background',
            field=models.ImageField(blank=True, null=True, upload_to='backgrounds/', verbose_name='Фоновое фото для страницы Отделения'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='events_background',
            field=models.ImageField(blank=True, null=True, upload_to='backgrounds/', verbose_name='Фоновое фото для страницы Мероприятия'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='gallery_background',
            field=models.ImageField(blank=True, null=True, upload_to='backgrounds/', verbose_name='Фоновое фото для страницы Галерея'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='reviews_background',
            field=models.ImageField(blank=True, null=True, upload_to='backgrounds/', verbose_name='Фоновое фото для страницы Отзывы'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='rewards_background',
            field=models.ImageField(blank=True, null=True, upload_to='backgrounds/', verbose_name='Фоновое фото для страницы Награды'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='teachers_background',
            field=models.ImageField(blank=True, null=True, upload_to='backgrounds/', verbose_name='Фоновое фото для страницы Учителя'),
        ),
    ]
