# Generated by Django 4.2.7 on 2026-04-06 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_sitesettings_contacts_background_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='application_type',
            field=models.CharField(choices=[('trial_lesson', 'Пробное занятие'), ('free_consultation', 'Бесплатная консультация'), ('event_registration', 'Запись на мероприятие')], default='trial_lesson', max_length=20, verbose_name='Тип заявки'),
        ),
    ]
