# Generated by Django 4.2.7 on 2026-04-06 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_alter_application_application_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='map_embed_code',
            field=models.TextField(blank=True, help_text='Вставьте HTML-код iframe карты Google или Яндекс.Карт', null=True, verbose_name='Карта на странице Контактов'),
        ),
    ]
