# Generated by Django 6.0.3 on 2026-04-11 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_alter_application_id_alter_department_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='text',
            field=models.CharField(max_length=255, verbose_name='Текст отзыва'),
        ),
    ]
